
CFLAGS := -Wall -O2 -g
CFLAGS += -I /home/orangepi/Linux_video/include  
obj-y += Convert_manager.o
obj-y += yuv2rgb.o
obj-y += color.o
obj-y += mjpeg2rgb.o
obj-y += jdatasrc-tj.o
obj-y += rgb2rgb.o
